# Project Name
TARGET = ShyTest

# Sources
CPP_SOURCES = ShyTest.cpp \
patch_bay.cpp \
resources.cpp \
fft_handler.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
